### ISSUE TITLE
Building error 'Debug Assertion failed'

### ISSUE THREAD

**Issue by magnificaiterata** [LegalizeAdulthood/iterated-dynamics#147]
I am getting this error when building the project from "Developer command prompt for Visual Studio" on a Windows 11 system. Any suggestions on how to get this please?

![image](https://github.com/user-attachments/assets/2cce5ace-cca9-479f-ba58-e600a607e776)

**Comment by LegalizeAdulthood** [comment]
Can you include the steps you used to configure and build the project?

BTW, you don't need to use a VS command-prompt to build Id, you can build it from any regular old command-prompt using the instructions in the readme.  CMake will locate your compiler from any command-prompt, not just a VS command prompt.

**Comment by magnificaiterata** [comment]
Of course, forgive the lack of details, I tend to get quite rambling and I wanted to avoid it this time.
Also, I didn't want to be smarmy but I think what you do with your dedication and your work is great; Thanks for that.
The build process I used is exactly the one indicated in the readme (by the way there is a syntax error in the git clone command 
"github.com:LegalizeAdulthood" instead of "github.com/LegalizeAdulthood"

git clone https://github.com:LegalizeAdulthood/iterated-dynamics
cd iterated-dynamics
git submodule init
git submodule update

cmake --workflow --preset default

I include the console output, however I do not locate the dump file that reports that it has been generated at the end of the process

![image](https://github.com/user-attachments/assets/ce4fedc7-f293-4400-abad-104554d72199)
[build-id.txt](https://github.com/user-attachments/files/17249319/build-id.txt)

Thanks a lot for the interest!

**Comment by LegalizeAdulthood** [comment]
Thanks, that confirms my suspicion that it is getting this error while attempting to build the documentation text file.  I'll take a look at the crash dump and see what I can figure out from there.

I had to disable the Windows Debug continuous integration build because it would hang while building the documentation text file.  I wasn't able to figure out why that was hanging, but now with your crash dump and this bug report, I think I have an idea what might be going wrong and why I couldn't reproduce it on my system.  (See #140)

**Comment by LegalizeAdulthood** [comment]
OK, I was able to reproduce the problem and correct it.  Try pulling HEAD on master and see if it corrects it for you; it also corrected the issue with the CI Debug builds as I suspected.

**Comment by magnificaiterata** [comment]
Built successfully! Thanks a lot
